# Generated by Django 5.2.7 on 2025-12-19 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
