# Generated by Django 5.2.7 on 2025-11-07 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_platform_game_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_critic', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.platform')),
            ],
        ),
    ]
