# Generated by Django 5.2.7 on 2025-12-12 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_release_date'),
        ('reviews', '0003_review_created_at_alter_review_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
